server:
    port: 8080

spring:
    datasource:
        platform: postgres
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://localhost:5432/management
        username: management
        password: management
    jpa:
        show-sql: false
        hibernate.ddl-auto: validate

management-app:
    security:
        token:
            tokenValidity: 1800