server:
    port: 8080

spring:
    datasource:
        platform: h2
        url: jdbc:h2:mem:management;DB_CLOSE_DELAY=-1
        username: management
        password: management
    jpa:
        show-sql: true
        hibernate.ddl-auto: validate

jasypt:
    encryptor:
        password: test-password

management-app:
    security:
        token:
            tokenValidity: 1800
            generateOnRestart: false
            token: ENC(uHE0CSkLrSSHW2T8A93mVVulsl3vlMce)