server:
    port: 8080

spring:
    datasource:
        platform: h2
        url: jdbc:h2:mem:management;DB_CLOSE_DELAY=-1
        username: management
        password: management
    jpa:
        show-sql: true
        hibernate.ddl-auto: validate

management-app:
    security:
        token:
            tokenValidity: 1800